# Generated by Django 3.2.8 on 2022-02-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0003_employee_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='location',
            field=models.CharField(max_length=40),
        ),
    ]
