# Generated by Django 3.2.8 on 2022-02-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0004_alter_office_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=20),
        ),
        migrations.AlterField(
            model_name='office',
            name='location',
            field=models.CharField(max_length=60),
        ),
    ]
